/*
 * This file was automatically generated by EvoSuite
 * Thu Mar 01 01:41:05 GMT 2018
 */

package familytree.model;

import org.junit.Test;
import static org.junit.Assert.*;
import familytree.model.PersonTest;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class PersonTest_ESTest extends PersonTest_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      PersonTest personTest0 = new PersonTest();
      personTest0.testRelationships();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      PersonTest personTest0 = new PersonTest();
      personTest0.testComplexRelationPreventer();
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      String[] stringArray0 = new String[6];
      PersonTest.main(stringArray0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      PersonTest personTest0 = new PersonTest();
      personTest0.testParentChildRelationship();
  }
}
